employeesDetails = [
  {
    empId: 1,
    empName: "Ram Kumar",
    dob: "03-12-2001",
    mailId: "ramkumar@gmail.com",
    phoneNumber: "6734743765",
    address: {
      doorNo: 31,
      road: "VRK Nagar Pudukottai",
      city: "Pudukottai",
      pincode: 601120,
    },
    experience: 7,
  },
  {
    empId: 2,
    empName: "Sita Devi",
    dob: "10-05-1995",
    mailId: "sitadevi@gmail.com",
    phoneNumber: "7890123456",
    address: {
      doorNo: 45,
      road: "MG Road",
      city: "Bangalore",
      pincode: 560001,
    },
    experience: 5,
  },
  {
    empId: 3,
    empName: "Rajesh Sharma",
    dob: "15-09-1980",
    mailId: "rajesh.sharma@gmail.com",
    phoneNumber: "9876543210",
    address: {
      doorNo: 12,
      road: "Park Street",
      city: "Kolkata",
      pincode: 700016,
    },
    experience: 15,
  },
  {
    empId: 4,
    empName: "Anjali Gupta",
    dob: "22-07-1992",
    mailId: "anjali.gupta@gmail.com",
    phoneNumber: "8765432109",
    address: {
      doorNo: 55,
      road: "Mount Road",
      city: "Chennai",
      pincode: 600002,
    },
    experience: 8,
  },
  {
    empId: 5,
    empName: "Kunal Patel",
    dob: "05-04-1985",
    mailId: "kunal.patel@gmail.com",
    phoneNumber: "7654321098",
    address: {
      doorNo: 23,
      road: "Link Road",
      city: "Mumbai",
      pincode: 400064,
    },
    experience: 12,
  },
  {
    empId: 6,
    empName: "Priya Sharma",
    dob: "19-11-1990",
    mailId: "priya.sharma@gmail.com",
    phoneNumber: "8765987654",
    address: {
      doorNo: 8,
      road: "MG Road",
      city: "Pune",
      pincode: 411001,
    },
    experience: 10,
  },
  {
    empId: 7,
    empName: "Vikram Singh",
    dob: "14-03-1988",
    mailId: "vikram.singh@gmail.com",
    phoneNumber: "9876123456",
    address: {
      doorNo: 65,
      road: "Civil Lines",
      city: "Jaipur",
      pincode: 302006,
    },
    experience: 9,
  },
  {
    empId: 8,
    empName: "Neha Kapoor",
    dob: "28-06-1982",
    mailId: "neha.kapoor@gmail.com",
    phoneNumber: "8765432109",
    address: {
      doorNo: 34,
      road: "Rajaji Nagar",
      city: "Bengaluru",
      pincode: 560010,
    },
    experience: 14,
  },
  {
    empId: 9,
    empName: "Rahul Verma",
    dob: "07-09-1994",
    mailId: "rahul.verma@gmail.com",
    phoneNumber: "7654321098",
    address: {
      doorNo: 48,
      road: "Jubilee Hills",
      city: "Hyderabad",
      pincode: 500033,
    },
    experience: 6,
  },
  {
    empId: 10,
    empName: "Aarti Khanna",
    dob: "12-12-1986",
    mailId: "aarti.khanna@gmail.com",
    phoneNumber: "9876543210",
    address: {
      doorNo: 22,
      road: "Hazratganj",
      city: "Lucknow",
      pincode: 226001,
    },
    experience: 11,
  },
  {
    empId: 11,
    empName: "Rajat Gupta",
    dob: "25-01-1980",
    mailId: "rajat.gupta@gmail.com",
    phoneNumber: "7654987654",
    address: {
      doorNo: 37,
      road: "Pantheon Road",
      city: "Chennai",
      pincode: 600008,
    },
    experience: 17,
  },
  {
    empId: 12,
    empName: "Pooja Mehta",
    dob: "30-04-1991",
    mailId: "pooja.mehta@gmail.com",
    phoneNumber: "8765987654",
    address: {
      doorNo: 15,
      road: "Viman Nagar",
      city: "Pune",
      pincode: 411014,
    },
    experience: 9,
  },
  {
    empId: 13,
    empName: "Amit Kapoor",
    dob: "08-08-1987",
    mailId: "amit.kapoor@gmail.com",
    phoneNumber: "9876123456",
    address: {
      doorNo: 44,
      road: "Lalbagh Road",
      city: "Bengaluru",
      pincode: 560027,
    },
    experience: 13,
  },
  {
    empId: 14,
    empName: "Nisha Singh",
    dob: "17-03-1993",
    mailId: "nisha.singh@gmail.com",
    phoneNumber: "8765432109",
    address: {
      doorNo: 28,
      road: "Residency Road",
      city: "Jaipur",
      pincode: 302001,
    },
    experience: 8,
  },
  {
    empId: 15,
    empName: "Arjun Sharma",
    dob: "14-06-1985",
    mailId: "arjun.sharma@gmail.com",
    phoneNumber: "7654321098",
    address: {
      doorNo: 33,
      road: "Koramangala",
      city: "Bengaluru",
      pincode: 560095,
    },
    experience: 12,
  },
  {
    empId: 16,
    empName: "Ritu Verma",
    dob: "03-09-1989",
    mailId: "ritu.verma@gmail.com",
    phoneNumber: "9876543210",
    address: {
      doorNo: 55,
      road: "Banjara Hills",
      city: "Hyderabad",
      pincode: 500034,
    },
    experience: 10,
  },
  {
    empId: 17,
    empName: "Vikas Kapoor",
    dob: "19-12-1981",
    mailId: "vikas.kapoor@gmail.com",
    phoneNumber: "8765987654",
    address: {
      doorNo: 18,
      road: "Richmond Road",
      city: "Bengaluru",
      pincode: 560025,
    },
    experience: 14,
  },
  {
    empId: 18,
    empName: "Neeta Gupta",
    dob: "26-05-1990",
    mailId: "neeta.gupta@gmail.com",
    phoneNumber: "9876123456",
    address: {
      doorNo: 47,
      road: "Mount Road",
      city: "Chennai",
      pincode: 600001,
    },
    experience: 11,
  },
  {
    empId: 19,
    empName: "Rajat Mehta",
    dob: "09-08-1986",
    mailId: "rajat.mehta@gmail.com",
    phoneNumber: "8765432109",
    address: {
      doorNo: 25,
      road: "Shivaji Nagar",
      city: "Pune",
      pincode: 411005,
    },
    experience: 9,
  },
  {
    empId: 20,
    empName: "Preeti Singh",
    dob: "05-11-1995",
    mailId: "preeti.singh@gmail.com",
    phoneNumber: "7654321098",
    address: {
      doorNo: 38,
      road: "JLN Marg",
      city: "Jaipur",
      pincode: 302018,
    },
    experience: 6,
  },
];
